### ISSUE TITLE
400 Bad Request in `load_maintenance` method

### ISSUE THREAD

**Issue by kubasaw** [IoTLabs-pl/pyhOn#8]
For me beta 11 is not working with or without docker exec command

```
Error setting up entry xxxxxxxxxxxxx@gmail.com for hon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hon/__init__.py", line 34, in async_setup_entry
    hon = await Hon(
          ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/hon.py", line 75, in setup
    await self._create_appliance(appliance, self._api)
  File "/usr/local/lib/python3.12/site-packages/pyhon/hon.py", line 58, in _create_appliance
    await appliance.load_statistics()
  File "/usr/local/lib/python3.12/site-packages/pyhon/appliance.py", line 211, in load_statistics
    self._statistics |= await self.api.load_maintenance(self)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/api.py", line 177, in load_maintenance
    async with self._session.get(
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/handler/hon.py", line 40, in _request
    async with super()._request(method, *args, **kwargs) as response:
  File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyhon/connection/handler/base.py", line 78, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1093, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url='https://api-iot.he.services/commands/v1/maintenance-cycle?macAddress=XX-XX-XX-XX-XX-XX'
```

_Originally posted by @Doktor-X in https://github.com/IoTLabs-pl/hon/issues/2#issuecomment-2308118223_

**Comment by kubasaw** [comment]
Updated to beta 12 pyhon is 0.18.0b1
I have flexis plus AC

```
Home Assistant Core
2024-08-24 19:55:54.974 DEBUG (MainThread) [pyhon.connection.auth] Starting OAuth2 authorization
2024-08-24 19:55:56.570 DEBUG (MainThread) [pyhon.connection.auth] Logging in
2024-08-24 19:55:57.574 DEBUG (MainThread) [pyhon.connection.auth] Getting tokens
2024-08-24 19:55:59.662 DEBUG (MainThread) [pyhon.connection.auth] Trying to retrieve Cognito token
2024-08-24 19:56:01.087 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('pyhon.appliances.ac',) inside the event loop by custom integration 'hon' at custom_components/hon/__init__.py, line 34: hon = await Hon( (offender: /usr/local/lib/python3.12/site-packages/pyhon/appliance.py, line 52: self._extra: Optional[ApplianceBase] = importlib.import_module(), please create a bug report at https://github.com/IoTLabs-pl/hon/issues
2024-08-24 19:56:03.712 ERROR (MainThread) [pyhon.connection.handler.base] hOn Authentication Error
File "/usr/local/lib/python3.12/site-packages/pyhon/hon.py", line 75, in setup
File "/usr/local/lib/python3.12/site-packages/pyhon/hon.py", line 58, in _create_appliance
File "/usr/local/lib/python3.12/site-packages/pyhon/appliance.py", line 211, in load_statistics
File "/usr/local/lib/python3.12/site-packages/pyhon/connection/api.py", line 177, in load_maintenance
File "/usr/local/lib/python3.12/site-packages/pyhon/connection/handler/hon.py", line 40, in _request
File "/usr/local/lib/python3.12/site-packages/pyhon/connection/handler/base.py", line 79, in _request
```
_Originally posted by @Doktor-X in https://github.com/IoTLabs-pl/hon/issues/2#issuecomment-2308476299_
